from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Tuple


def _copy_value(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _copy_value(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_copy_value(item) for item in value]
    return value


def _copy_records(records: Tuple[Dict[str, Any], ...]) -> list:
    return [_copy_value(record) for record in records]


@dataclass(frozen=True)
class AppShellSpec(object):
    app_commands: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    workspace_commands: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    workbench_commands: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    command_palette_groups: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    command_palette_labels: Dict[str, Any] = field(default_factory=dict)
    chrome: Dict[str, Any] = field(default_factory=dict)
    surface_chrome: Dict[str, Any] = field(default_factory=dict)
    right_panel_surfaces: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    bottom_drawer_surfaces: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    keybindings: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    source_control: Dict[str, Any] = field(default_factory=dict)
    terminal: Dict[str, Any] = field(default_factory=dict)
    preview: Dict[str, Any] = field(default_factory=dict)
    thread_lifecycle_actions: Tuple[Dict[str, Any], ...] = field(default_factory=tuple)
    home: Dict[str, Any] = field(default_factory=dict)

    def capabilities(self) -> Dict[str, Any]:
        return {
            "app_commands": _copy_records(self.app_commands),
            "workspace_commands": _copy_records(self.workspace_commands),
            "workbench_commands": _copy_records(self.workbench_commands),
            "command_palette": {
                "groups": _copy_records(self.command_palette_groups),
                "labels": _copy_value(self.command_palette_labels),
            },
            "chrome": _copy_value(self.chrome),
            "surfaces": {
                "right_panel": _copy_records(self.right_panel_surfaces),
                "bottom_drawer": _copy_records(self.bottom_drawer_surfaces),
                "chrome": _copy_value(self.surface_chrome),
            },
            "keybindings": _copy_records(self.keybindings),
            "source_control": _copy_value(self.source_control),
            "terminal": _copy_value(self.terminal),
            "preview": _copy_value(self.preview),
            "thread_lifecycle": {
                "actions": _copy_records(self.thread_lifecycle_actions),
            },
            "home": _copy_value(self.home),
        }


def _surface(surface_id: str, title: str, launcher_order: int, **metadata: Any) -> Dict[str, Any]:
    record = {
        "id": surface_id,
        "title": title,
        "launcher_order": launcher_order,
    }
    record.update(metadata)
    return record


def _keybinding(key: str, command_id: str, when: str = "always") -> Dict[str, Any]:
    return {
        "key": key,
        "command_id": command_id,
        "when": when,
    }


def _command(
    command_id: str,
    group: str,
    label: str,
    order: int,
    **metadata: Any,
) -> Dict[str, Any]:
    record = {
        "id": command_id,
        "group": group,
        "label": label,
        "order": order,
        "visible_when": "always",
    }
    record.update(metadata)
    return record


def _palette_group(
    group_id: str,
    title: str,
    description: str,
    order: int,
    **metadata: Any,
) -> Dict[str, Any]:
    record = {
        "id": group_id,
        "title": title,
        "description": description,
        "order": order,
    }
    record.update(metadata)
    return record


def _thread_lifecycle_action(
    action_id: str,
    label: str,
    order: int,
    **metadata: Any,
) -> Dict[str, Any]:
    record = {
        "id": action_id,
        "label": label,
        "capability": action_id,
        "order": order,
    }
    record.update(metadata)
    return record


def default_app_shell_spec() -> AppShellSpec:
    return AppShellSpec(
        app_commands=(
            _command("app.settings", "app", "Open Settings", 10, surface="settings"),
            _command(
                "app.diagnostics",
                "app",
                "Open Diagnostics",
                20,
                surface="diagnostics",
            ),
            _command(
                "app.source_control",
                "app",
                "Open Source Control",
                30,
                surface="source_control",
                keywords=["git", "changes", "source", "source_control"],
            ),
            _command("app.reload", "app", "Reload App Shell", 40),
        ),
        workspace_commands=(
            _command(
                "workspace.open",
                "workspace",
                "Open Workspace",
                10,
                keywords=["project", "folder"],
            ),
            _command(
                "workspace.refresh",
                "workspace",
                "Refresh Workspaces",
                20,
                keywords=["reload", "recent"],
            ),
            _command(
                "workspace.remove_current",
                "workspace",
                "Remove Current Workspace From Recents",
                30,
                visible_when="has_workspace",
                keywords=["forget", "recent"],
            ),
        ),
        workbench_commands=(
            _command("session.new", "session", "New Session", 10, slash="/new"),
            _command(
                "thread.new",
                "session",
                "New Thread",
                20,
                slash="",
                keywords=["session", "chat"],
            ),
            _command(
                "session.refresh",
                "session",
                "Refresh Sessions",
                30,
                slash="/sessions",
            ),
            _command(
                "session.resume",
                "session",
                "Resume Session",
                40,
                slash="/resume",
            ),
            _command(
                "message.send",
                "message",
                "Send Message",
                10,
                visible_when="composer_ready",
            ),
            _command(
                "message.stop",
                "message",
                "Stop Running Turn",
                20,
                visible_when="running",
            ),
            _command(
                "view.toggle_right_panel",
                "view",
                "Toggle Right Panel",
                10,
            ),
            _command(
                "view.toggle_bottom_drawer",
                "view",
                "Toggle Bottom Drawer",
                20,
            ),
            _command(
                "palette.open",
                "view",
                "Open Command Palette",
                30,
            ),
            _command(
                "palette.close",
                "view",
                "Close Command Palette",
                40,
                visible_when="palette_open",
            ),
        ),
        command_palette_groups=(
            _palette_group("app", "App", "App shell commands", 10),
            _palette_group("session", "Sessions", "Create, refresh, and resume threads", 20),
            _palette_group("message", "Message", "Send or stop the current turn", 30),
            _palette_group("mode", "Mode", "Switch the active agent mode", 40),
            _palette_group("surface", "Surface", "Open workbench surfaces", 50),
            _palette_group("workspace", "Workspace", "Open or refresh local workspaces", 60),
            _palette_group("workflow", "Workflow", "Run workflow views", 70),
            _palette_group("view", "View", "Toggle workbench layout", 80),
        ),
        command_palette_labels={
            "root_title": "Command palette",
            "submenu_title": "Command group",
            "search_label": "Command search",
            "root_placeholder": "Search commands, sessions, workspaces",
            "submenu_placeholder": "Search this group",
            "root_empty": "No matching commands, sessions, or workspaces",
            "submenu_empty": "No matching commands in this group",
            "commands_section": "Commands",
            "sessions_section": "Sessions",
            "workspaces_section": "Workspaces",
            "current_label": "Current",
            "missing_label": "Missing",
            "workspace_meta": "Workspace",
            "workspace_fallback": "Workspace",
            "session_fallback_prefix": "Session",
        },
        chrome={
            "brand_subtitle": "Local agent workbench",
            "sidebar_aria_label": "Sidebar",
            "thread_panel_aria_label": "Chats",
            "header": {
                "command_palette_label": "Command palette",
                "command_palette_short_label": "Cmd",
                "refresh_label": "Refresh",
                "bottom_drawer_label": "Run",
                "bottom_drawer_title": "Toggle run output",
                "right_panel_label": "Panel",
                "right_panel_title": "Toggle right panel",
                "turns_label": "turns",
            },
            "composer": {
                "placeholder": "Message",
                "command_palette_label": "Open command palette",
                "send_label": "Send",
                "stop_label": "Stop",
                "command_menu": {
                    "path_group_label": "Files",
                    "command_group_fallback_label": "Command",
                    "path_empty_text": "No files found",
                    "command_empty_text": "No commands found",
                    "default_empty_text": "No matches",
                    "path_aria_label": "File context suggestions",
                    "command_aria_label": "Slash command suggestions",
                    "path_item_kind_label": "file",
                    "command_item_kind_label": "command",
                },
                "hints": {
                    "command": "/ commands",
                    "file": "@ files",
                    "select": "select",
                    "newline": "Shift+Enter newline",
                    "status.running": "running turns disable editing",
                    "status.interaction": "interaction pending",
                },
            },
            "interaction": {
                "pending_approval_kicker": "PENDING APPROVAL",
                "input_required_kicker": "INPUT REQUIRED",
                "command_approval_summary": "Command approval requested",
                "file_read_approval_summary": "File-read approval requested",
                "file_change_approval_summary": "File-change approval requested",
                "expired_title": "Interaction expired",
                "expired_body": (
                    "This request is no longer active. Trigger the action again to continue."
                ),
                "conflict_title": "Interaction already handled",
                "conflict_body": (
                    "This request changed in another flow. Refresh the current interaction "
                    "and try again if needed."
                ),
                "approve_once_label": "Approve once",
                "decline_label": "Decline",
                "cancel_turn_label": "Cancel turn",
                "always_allow_session_label": "Always allow this session",
                "input_summary": "Input requested",
                "custom_answer_placeholder": "Or type a custom answer...",
                "submit_label": "Submit",
                "mode_label_prefix": "mode:",
            },
            "surface_panel": {
                "aria_label": "Surface panel",
                "settings_title": "Settings",
                "confirm_workspace_switch_label": "Confirm workspace switch",
                "show_diagnostics_badge_label": "Show diagnostics badge",
                "diagnostics_title": "Diagnostics",
                "capabilities_title": "Capabilities",
                "no_diagnostics": "No app diagnostics loaded.",
                "plan_title": "Plan",
                "no_plan": "No active plan in this session.",
                "diagnostic_groups": {
                    "host": "Host",
                    "runtime": "Runtime",
                    "renderer": "Renderer",
                    "workspace_registry": "Workspace Registry",
                    "active_core": "Active Core",
                },
            },
            "timeline": {
                "aria_label": "Conversation",
                "empty_state": "No conversation yet.",
                "history_partial_label": "history partially restored",
                "history_partial_fallback": "restore stopped early",
                "history_unavailable": "session history unavailable",
                "explicit_loop_limit_reached": "Explicit loop safety limit reached.",
                "max_turn_limit_template": "Maximum turn limit reached ({turnsUsed}/{maxTurns}).",
                "guard_stopped": "Stopped by guard.",
                "cancelled": "Cancelled.",
                "changed_files": {
                    "summary_template": "{count} changed files",
                    "expand_label": "Expand",
                    "collapse_label": "Collapse",
                    "view_diff_label": "View diff",
                },
                "work_group": {
                    "singular_label": "1 tool call",
                    "plural_label_template": "{count} tool calls",
                    "show_fewer_label": "Show fewer tool calls",
                    "previous_singular_template": "+{count} previous tool call",
                    "previous_plural_template": "+{count} previous tool calls",
                },
                "activity_rows": {
                    "working_label": "Working...",
                    "working_active_prefix": "Working for",
                    "turn_fold_label": "Worked for this turn",
                    "turn_fold_duration_template": "Worked for {duration}",
                    "turn_fold_stopped_duration_template": "You stopped after {duration}",
                    "turn_fold_stopped_label": "You stopped this response",
                    "turn_fold_step_singular_template": "{count} step",
                    "turn_fold_step_plural_template": "{count} steps",
                    "interaction_label": "interaction",
                    "interaction_pending_status": "pending",
                    "reasoning_label": "Thinking",
                    "thinking_label": "Thinking",
                    "streaming_status": "streaming",
                    "word_singular_template": "{count} word",
                    "word_plural_template": "{count} words",
                    "context_updated": "Context updated",
                    "context_summarized_template": "{count} summarized",
                    "context_retained_template": "{count} retained",
                    "context_size_template": "~{count} units",
                    "metadata_separator": " / ",
                    "command_default_name": "command",
                    "command_failed_status": "failed",
                    "command_completed_status": "completed",
                    "review_label": "/review",
                    "review_singular_finding": "1 finding",
                    "review_plural_findings_template": "{count} findings",
                    "timer_zero_label": "0s",
                    "timer_seconds_template": "{seconds}s",
                    "timer_minutes_seconds_template": "{minutes}m {seconds}s",
                    "timer_hours_minutes_template": "{hours}h {minutes}m",
                },
                "tool_detail": {
                    "default_section_title": "Details",
                    "fallback_match_label": "match",
                    "field_labels": {
                        "path": "path",
                        "pattern": "pattern",
                        "recipe": "recipe",
                        "target": "target",
                        "command": "command",
                        "cwd": "cwd",
                        "exit": "exit",
                        "lines": "lines",
                        "chars": "chars",
                        "matches": "matches",
                        "returned": "returned",
                    },
                    "section_titles": {
                        "error": "Error",
                        "preview": "Preview",
                        "summary": "Summary",
                        "matches": "Matches",
                        "files": "Files",
                        "stdout": "stdout",
                        "stderr": "stderr",
                        "diff": "Diff",
                        "changed_files": "Changed files",
                    },
                },
                "work_row": {
                    "default_heading": "Work",
                    "default_icon_name": "zap",
                    "status_labels": {
                        "failure": "failed",
                        "success": "completed",
                        "neutral": "empty",
                        "interrupted": "cancelled",
                        "discarded": "skipped",
                    },
                },
            },
        },
        surface_chrome={
            "right_panel_aria_label": "Right panel",
            "add_surface_label": "Add panel surface",
            "empty_title": "Open a surface",
            "empty_body": "Choose what to show in the right panel.",
            "surface_actions_label_prefix": "Surface actions for",
            "close_label_prefix": "Close",
            "close_action_label": "Close",
            "close_others_action_label": "Close others",
            "close_to_right_action_label": "Close to the right",
            "close_all_action_label": "Close all",
            "default_icon": "S",
            "bottom_drawer_aria_label": "Bottom drawer",
            "run_output_empty_message": "No run output yet.",
            "termination_reason_prefix": "reason",
            "file_preview": {
                "default_file_title": "File",
                "default_project_label": "Workspace",
                "loading_message": "Loading file...",
                "unavailable_message": "File unavailable",
                "retry_label": "Retry",
                "copy_path_title_template": "Copy {title} path",
                "show_markdown_source_label": "Show markdown source",
                "show_rendered_markdown_label": "Show rendered markdown",
                "show_file_explorer_label": "Show file explorer",
                "metadata_separator": " / ",
                "line_singular_label": "line",
                "line_plural_label": "lines",
                "plain_language_label": "Plain",
                "language_labels": {
                    "c": "C",
                    "c_header": "C Header",
                    "cpp": "C++",
                    "cpp_header": "C++ Header",
                    "python": "Python",
                    "javascript": "JavaScript",
                    "typescript": "TypeScript",
                    "json": "JSON",
                    "markdown": "Markdown",
                    "css": "CSS",
                    "html": "HTML",
                    "shell": "Shell",
                    "powershell": "PowerShell",
                    "toml": "TOML",
                    "yaml": "YAML",
                    "text": "Text",
                },
            },
            "diff_panel": {
                "default_title": "Diff",
                "empty_message": "No diff selected.",
                "selection_aria_label": "Diff selection",
                "controls_aria_label": "Diff controls",
                "stacked_title": "Stacked diff view",
                "split_title": "Split diff view",
                "enable_word_wrap_title": "Enable line wrapping",
                "disable_word_wrap_title": "Disable line wrapping",
                "hide_whitespace_title": "Hide whitespace changes",
                "show_whitespace_title": "Show whitespace changes",
                "changed_files_aria_label": "Changed files",
                "files_label": "Files",
                "expand_file_label_template": "Expand {path}",
                "collapse_file_label_template": "Collapse {path}",
                "expand_diff_label": "Expand diff",
                "source_control_title_template": "Git Diff: {path}",
            },
        },
        right_panel_surfaces=(
            _surface(
                "preview",
                "Preview",
                10,
                icon="B",
                description="Open a local browser preview.",
                command=True,
                command_label="Open Preview",
                slash="/preview",
                visible_when="always",
                default_resource_id="",
                close_behavior="closable",
                keywords=["browser", "localhost", "web"],
            ),
            _surface(
                "files",
                "Files",
                20,
                icon="F",
                description="Browse workspace files.",
                command=True,
                command_label="Open Files",
                slash="/workspace",
                visible_when="always",
                default_resource_id="",
                close_behavior="closable",
            ),
            _surface(
                "terminal",
                "Terminal",
                30,
                icon="T",
                description="Use a shell in this workspace.",
                command=True,
                command_label="Open Terminal",
                slash="",
                visible_when="has_session",
                default_resource_id="",
                close_behavior="closable",
            ),
            _surface(
                "diff",
                "Diff",
                40,
                icon="D",
                description="Review local changes.",
                command=True,
                command_label="Open Diff",
                slash="/diff",
                visible_when="always",
                default_resource_id="current",
                close_behavior="closable",
                keywords=["git", "changes", "diff"],
            ),
            _surface(
                "plan",
                "Plan",
                50,
                icon="P",
                description="Inspect the current plan.",
                command=True,
                command_label="Open Plan",
                slash="/plan",
                visible_when="always",
                default_resource_id="",
                close_behavior="closable",
            ),
            _surface(
                "source_control",
                "Source Control",
                60,
                icon="S",
                description="Review local Git status.",
                command=True,
                command_label="Open Source Control",
                slash="",
                visible_when="always",
                default_resource_id="",
                close_behavior="closable",
                read_only=True,
                offline=True,
                keywords=["git", "changes", "local"],
            ),
            _surface(
                "settings",
                "Settings",
                70,
                icon="G",
                description="Adjust app-shell preferences.",
                command=True,
                command_label="Open Settings",
                slash="",
                visible_when="always",
                default_resource_id="",
                close_behavior="closable",
            ),
            _surface(
                "diagnostics",
                "Diagnostics",
                80,
                icon="I",
                description="Inspect app-shell health.",
                command=True,
                command_label="Open Diagnostics",
                slash="",
                visible_when="always",
                default_resource_id="",
                close_behavior="closable",
            ),
        ),
        bottom_drawer_surfaces=(
            _surface(
                "run_output",
                "Run Output",
                10,
                icon="R",
                description="Show turn and tool output.",
                command=True,
                command_label="Toggle Run Output",
                visible_when="always",
                close_behavior="pinned",
            ),
            _surface(
                "terminal",
                "Terminal",
                20,
                icon="T",
                description="Use a shell in this workspace.",
                command=True,
                command_label="Open Terminal",
                visible_when="has_session",
                close_behavior="pinned",
            ),
            _surface(
                "logs",
                "Logs",
                30,
                icon="L",
                description="Inspect renderer and runtime logs.",
                command=True,
                command_label="Open Logs",
                visible_when="always",
                close_behavior="pinned",
            ),
        ),
        keybindings=(
            _keybinding("mod+k", "palette.open", "not_palette"),
            _keybinding("escape", "palette.close", "palette"),
            _keybinding("escape", "message.stop", "running"),
            _keybinding("mod+b", "view.toggle_right_panel"),
            _keybinding("mod+,", "app.settings"),
            _keybinding("mod+j", "view.toggle_bottom_drawer"),
            _keybinding("mod+1", "surface.files"),
            _keybinding("mod+2", "surface.terminal"),
            _keybinding("mod+3", "surface.diff"),
            _keybinding("mod+4", "surface.preview"),
            _keybinding("mod+enter", "message.send", "composer"),
        ),
        source_control={
            "enabled": True,
            "vcs": ["git"],
            "read_only": True,
            "remote_providers": False,
            "network": False,
            "checkpoints": False,
            "requires_active_workspace": True,
            "chrome": {
                "title": "Source Control",
                "status_unavailable_notice": "Source control unavailable.",
                "diff_unavailable_notice": "Diff unavailable",
                "loading_message": "Loading changes...",
                "git_unavailable_message": "Git runtime is not available for this workspace.",
                "not_repository_message": "The active workspace is not a Git repository.",
                "clean_message": "No local changes.",
                "no_branch_label": "No branch",
                "runtime_git_label": "git",
                "missing_runtime_label": "missing",
                "refresh_label": "Refresh",
                "count_labels": {
                    "files": "files",
                    "staged": "staged",
                    "changed": "changed",
                    "untracked": "untracked",
                },
                "group_labels": {
                    "staged": "Staged",
                    "unstaged": "Changes",
                    "untracked": "Untracked",
                    "conflicted": "Conflicts",
                    "fallback": "Changes",
                },
                "provider_labels": {
                    "azure": "Azure Repos",
                    "bitbucket": "Bitbucket",
                    "gitea": "Gitea",
                    "github": "GitHub",
                    "gitlab": "GitLab",
                    "local": "Local Git",
                    "fallback": "Local Git",
                },
                "branch_toolbar": {
                    "default_workspace_label": "Workspace",
                    "loading_label": "Checking Git...",
                    "error_label": "Git status unavailable",
                    "git_unavailable_label": "Git unavailable",
                    "not_repository_label": "No repository",
                    "unknown_ref_label": "Unknown ref",
                    "detached_prefix": "detached",
                    "clean_label": "Clean",
                    "change_singular": "change",
                    "change_plural": "changes",
                    "conflict_singular": "conflict",
                    "conflict_plural": "conflicts",
                    "current_checkout_label": "Current checkout",
                    "current_checkout_description": ("Run in the active workspace checkout."),
                    "git_unavailable_reason": (
                        "Git is unavailable in this offline bundle or workspace."
                    ),
                    "not_repository_reason": ("This workspace is not a Git repository."),
                    "error_reason_fallback": "Git status is unavailable.",
                    "read_only_action_title": (
                        "This action is read-only in the current GUI shell."
                    ),
                    "worktree_action_label": "Worktree",
                    "branch_action_label": "Branch",
                    "refresh_label": "Refresh",
                    "refresh_title": "Refresh local Git status",
                    "metadata_separator": " / ",
                },
            },
        },
        terminal={
            "enabled": True,
            "pty": False,
            "resize": False,
            "history_persistent": False,
            "max_buffer_bytes": 131072,
            "chrome": {
                "title_prefix": "Terminal",
                "default_title": "Terminal",
                "session_required_notice": "Open a session before using the terminal.",
                "open_failed_notice": "Terminal failed to open.",
                "write_failed_notice": "Terminal write failed.",
                "clear_failed_notice": "Terminal clear failed.",
                "restart_failed_notice": "Terminal restart failed.",
                "close_failed_notice": "Terminal close failed.",
                "new_label": "New",
                "new_title": "New terminal",
                "split_label": "Split",
                "split_title": "Split terminal horizontally",
                "split_vertical_label": "Split V",
                "split_vertical_title": "Split terminal vertically",
                "drawer_label": "Drawer",
                "unavailable_message": "Terminal session is unavailable.",
                "command_placeholder": "Type a command",
                "clear_label": "Clear",
                "restart_label": "Restart",
                "close_label": "Close",
                "empty_message": "No terminal sessions for this thread yet.",
                "empty_action_label": "New terminal",
            },
        },
        preview={
            "enabled": True,
            "local_servers": [
                {"label": "Vite dev server", "url": "localhost:5173", "port": 5173},
                {"label": "Local app", "url": "127.0.0.1:8000", "port": 8000},
            ],
            "chrome": {
                "refresh_label": "Refresh",
                "loading_label": "Loading...",
                "refresh_aria_label": "Refresh preview",
                "loading_aria_label": "Loading preview",
                "url_placeholder": "Search or enter URL",
                "url_aria_label": "Preview URL",
                "open_external_label": "Open in system browser",
                "annotate_label": "Annotate preview",
                "more_actions_label": "More preview actions",
                "unavailable_title": "Preview unavailable",
                "unavailable_body": ("This local page cannot be rendered in the embedded preview."),
                "unreachable_body": "The local preview target did not respond.",
                "reload_label": "Reload",
                "failed_notice": "Preview failed",
                "refresh_failed_notice": "Preview refresh failed",
                "open_failed_notice": "Open preview failed",
                "session_required_notice": "Open a session before using preview.",
                "servers_title": "Local servers",
                "empty_title": "No preview open",
                "servers_description": "Choose a local server to open in the preview panel.",
                "empty_description": "Start a local dev server or enter a localhost URL above.",
                "local_server_fallback_label": "Local server",
                "status_loading": "Loading",
                "status_ready": "Ready",
                "status_failed": "Preview unavailable",
                "status_idle": "Idle",
            },
        },
        thread_lifecycle_actions=(
            _thread_lifecycle_action(
                "rename",
                "Rename",
                10,
                prompt_title="Rename thread",
                empty_title="Rename failed",
                empty_body="Thread title cannot be empty.",
                failure_title="Rename failed",
            ),
            _thread_lifecycle_action(
                "fork",
                "Fork",
                20,
                prompt_title="Fork thread title",
                prompt_initial="",
                failure_title="Fork failed",
            ),
            _thread_lifecycle_action(
                "archive",
                "Archive",
                30,
                danger=True,
                confirm_title="Archive this thread?",
                success_title="Thread archived",
                success_body="The thread was archived and hidden from the normal thread list.",
                failure_title="Archive failed",
            ),
        ),
        home={
            "workspace": {
                "section_title": "Project",
                "inactive_label": "No workspace",
                "inactive_path": "Open a local project",
                "path_placeholder": "Workspace path",
                "open_label": "Open",
                "open_aria_label": "Open workspace",
                "recents_label": "Recent projects",
                "missing_path_label": "Missing path",
                "remove_label": "Remove",
            },
            "threads": {
                "section_title": "Threads",
                "new_label": "New",
                "empty_title": "No threads yet",
                "empty_body": "Start one for this project.",
                "active_label": "active",
                "actions_label_prefix": "Thread actions for",
            },
        },
    )
