from __future__ import annotations

C_WORKFLOW_TOOL_METADATA = {
    "list_recipes": {
        "permission_category": "read",
        "mode_visibility": ["build", "debug", "verify"],
        "workflow_visibility": ["chat", "plan", "review", "command"],
        "user_label": "List Recipes",
        "progress_renderer_key": "recipe",
        "result_renderer_key": "recipe",
        "supports_diff_preview": False,
        "context_reducer_key": "list_recipes",
        "read_only": True,
        "concurrency_safe": True,
        "interrupt_behavior": "block",
        "result_budget_policy": "compact-preview",
        "activity_kind": "recipe",
        "context_priority": 70,
    },
    "run_recipe": {
        "permission_category": "toolchain_exec",
        "mode_visibility": ["build", "debug", "verify"],
        "workflow_visibility": ["chat", "plan", "review", "command"],
        "user_label": "Run Recipe",
        "progress_renderer_key": "toolchain",
        "result_renderer_key": "toolchain",
        "supports_diff_preview": False,
        "context_reducer_key": "run_recipe",
        "read_only": False,
        "concurrency_safe": False,
        "interrupt_behavior": "cancel",
        "result_budget_policy": "artifact-first",
        "activity_kind": "diagnostic",
        "context_priority": 100,
        "read_model_invalidations": ["tasks"],
    },
    "report_quality_v2": {
        "permission_category": "read",
        "mode_visibility": ["verify"],
        "workflow_visibility": ["chat", "plan", "review", "command"],
        "user_label": "Quality Report V2",
        "progress_renderer_key": "quality",
        "result_renderer_key": "quality",
        "supports_diff_preview": False,
        "context_reducer_key": "report_quality_v2",
        "read_only": True,
        "concurrency_safe": True,
        "interrupt_behavior": "block",
        "result_budget_policy": "compact-preview",
        "activity_kind": "diagnostic",
        "context_priority": 88,
        "read_model_invalidations": ["tasks"],
    },
    "task_status": {
        "permission_category": "read",
        "mode_visibility": ["build", "debug", "verify"],
        "workflow_visibility": ["chat", "plan", "review", "command"],
        "user_label": "Task Status",
        "progress_renderer_key": "tasks",
        "result_renderer_key": "tasks",
        "supports_diff_preview": False,
        "context_reducer_key": "task_status",
        "read_only": True,
        "concurrency_safe": True,
        "interrupt_behavior": "block",
        "result_budget_policy": "compact-preview",
        "activity_kind": "task",
        "context_priority": 98,
        "read_model_invalidations": ["tasks"],
    },
    "record_failing_evidence": {
        "permission_category": "read",
        "mode_visibility": ["debug"],
        "workflow_visibility": ["chat", "plan", "review", "command"],
        "user_label": "Record Failing Evidence",
        "progress_renderer_key": "default",
        "result_renderer_key": "default",
        "supports_diff_preview": False,
        "context_reducer_key": "record_failing_evidence",
        "read_only": True,
        "concurrency_safe": True,
        "interrupt_behavior": "block",
        "result_budget_policy": "compact-preview",
        "activity_kind": "diagnostic",
        "context_priority": 82,
        "read_model_invalidations": ["tasks"],
    },
}
