/**
 * All user-visible strings, keyed by ID.
 * Add a new language by adding a matching key block.
 */
const STRINGS = {
  en: {
    // Brand
    "brand.sub": "Codex-grade local shell",

    // Sidebar
    "sidebar.chats": "Chats",
    "sidebar.files": "Files",
    "sidebar.newSession": "New Session",

    // Inspector tabs
    "inspector.todos": "Todos",
    "inspector.artifacts": "Artifacts",
    "inspector.plan": "Plan",
    "inspector.run": "Run",
    "inspector.runRecipe": "Run Recipe",
    "inspector.runTarget": "Target (optional)",
    "inspector.runProfile": "Profile (optional)",
    "inspector.problems": "Problems",
    "inspector.review": "Review",
    "inspector.permissions": "Permissions",
    "inspector.runtime": "Runtime",
    "inspector.reviewEvidence": "Evidence",
    "inspector.reviewDiagnostics": "Diagnostics",
    "inspector.reviewTests": "Tests",
    "inspector.reviewCoverage": "Coverage",
    "inspector.reviewQuality": "Quality Gate",
    "inspector.reviewGit": "Git",
    "inspector.rulesPath": "Rules path",
    "inspector.remembered": "Remembered categories",
    "inspector.ruleCount": "Rule count",
    "inspector.rememberedCategories": "Remembered Categories",
    "inspector.permissionRules": "Permission Rules",
    "inspector.ruleTools": "Tools",
    "inspector.rulePaths": "Paths",
    "inspector.ruleCwds": "Working dirs",
    "inspector.ruleCommands": "Command patterns",
    "inspector.testPassed": "Passed",
    "inspector.testFailed": "Failed",
    "inspector.testSkipped": "Skipped",
    "inspector.testTotal": "Total",
    "inspector.qualityPassed": "Passed",
    "inspector.qualityFailed": "Failed",
    "inspector.gitFiles": "Files",
    "inspector.gitLines": "Lines",
    "inspector.gitAvailable": "Git",
    "inspector.yes": "Yes",
    "inspector.no": "No",
    "inspector.openEvidence": "Open in Preview",
    "inspector.openDiff": "Open Diff",
    "inspector.preview": "Preview",
    "inspector.log": "Log",
    "inspector.runtimeSource": "Source",
    "inspector.runtimeReady": "Managed tools ready",
    "inspector.runtimeResolvedRoots": "Resolved roots",
    "inspector.runtimeToolSources": "Tool sources",
    "inspector.runtimeWarnings": "Warnings",
    "inspector.sessionStatus": "Session status",
    "inspector.lastState": "Last state",
    "inspector.lastStateMessage": "Last state detail",
    "inspector.timelineProjection": "Timeline projection",
    "inspector.recentTransitions": "Recent transitions",
    "inspector.noRecentTransitions": "No recent transitions.",

    // Panel empty states
    "inspector.noTodos": "No todos in this session.",
    "inspector.noArtifacts": "No artifacts yet.",
    "inspector.noPlan": "No active plan in this session.",
    "inspector.noRecipes": "No workspace recipes detected.",
    "inspector.noProblems": "No current diagnostics or failing tests.",
    "inspector.noReview": "No review results yet.",
    "inspector.noReviewFindings": "No structured findings.",
    "inspector.noReviewEvidence": "No structured evidence.",
    "inspector.noPermissions": "No permission context loaded.",
    "inspector.noRuntime": "No runtime context loaded.",
    "inspector.noPermissionRules": "No permission rules configured.",
    "inspector.noPreview": "Select a file or artifact to preview.",
    "inspector.noLog": "No events yet.",
    "inspector.noRuntimeWarnings": "No runtime warnings.",

    // User input panel
    "inspector.inputRequired": "Input Required",
    "inspector.customAnswer": "Or type a custom answer…",
    "inspector.submit": "Submit",

    // Composer
    "composer.placeholder": "Message… Enter to send, Shift+Enter for newline",
    "composer.send": "Send",
    "composer.stop": "Stop",

    // Header
    "header.refresh": "Refresh",
    "header.toggleInspector": "Toggle inspector panel",

    // Timeline
    "timeline.thinking": "Thinking…",
    "timeline.thinkingLabel": "Thinking",
    "timeline.thinkingWords": "{n} words",
    "timeline.stepLabel": "Step {n}",
    "timeline.toolDetails": "Details",
    "timeline.diffChanges": "File changes",
    "timeline.runningToolchain": "Toolchain step is running…",
    "timeline.runningCommand": "Command is running…",
    "timeline.runningGit": "Git operation is running…",
    "timeline.toolchainTests": "{n} failing tests",
    "timeline.toolchainDiagnostics": "{n} diagnostics",
    "timeline.commandExitCode": "Exit code {n}",
    "timeline.gitFilesChanged": "{n} files changed",
    "timeline.gitEntries": "{n} git entries",
    "timeline.qualityPassed": "Quality gate passed",
    "timeline.qualityFailed": "{n} quality gate reasons",
    "timeline.todoCount": "{n} todos",
    "timeline.residualRisks": "Residual Risks",
    "timeline.compacted": "Context compacted",
    "timeline.compactSummarized": "summarized",
    "timeline.compactRetained": "retained",
    "timeline.toolInterrupted": "Cancelled",
    "timeline.toolDiscarded": "Skipped (retry boundary)",
    "timeline.maxTurnsReached": "Reached {max}-turn limit ({used} used). Continue by sending a new message.",
    "timeline.guardStop": "Repeated failures detected. Agent stopped. Describe the issue or adjust direction to continue.",
    "timeline.cancelled": "Cancelled.",
    "inspector.compactRetryCount": "Compact retries",
    "inspector.compactBoundaryCount": "Compact boundaries",
    "inspector.contextPipelineSteps": "Context pipeline",

    // Todos
    "todos.title": "Session Todos",
    "todos.done": "done",
    "todos.todo": "todo",

    // Artifacts
    "artifacts.title": "Artifacts",

    // Permission modal
    "modal.permissionRequired": "Permission Required",
    "modal.tool": "Tool",
    "modal.showDetails": "Show details",
    "modal.remember": "Remember for this session",
    "modal.deny": "Deny",
    "modal.approve": "Approve",

    // Language toggle (shows what you switch TO)
    "lang.toggle": "中文",
  },

  zh: {
    "brand.sub": "本地离线编码助手",

    "sidebar.chats": "对话",
    "sidebar.files": "文件",
    "sidebar.newSession": "新建会话",

    "inspector.todos": "待办",
    "inspector.artifacts": "产物",
    "inspector.plan": "计划",
    "inspector.run": "运行",
    "inspector.runRecipe": "执行 Recipe",
    "inspector.runTarget": "目标（可选）",
    "inspector.runProfile": "配置（可选）",
    "inspector.problems": "问题",
    "inspector.review": "审查",
    "inspector.permissions": "权限",
    "inspector.runtime": "运行环境",
    "inspector.reviewEvidence": "证据",
    "inspector.reviewDiagnostics": "诊断",
    "inspector.reviewTests": "测试",
    "inspector.reviewCoverage": "覆盖率",
    "inspector.reviewQuality": "质量门",
    "inspector.reviewGit": "Git",
    "inspector.rulesPath": "规则路径",
    "inspector.remembered": "已记住类别",
    "inspector.ruleCount": "规则数量",
    "inspector.rememberedCategories": "已记住的类别",
    "inspector.permissionRules": "权限规则",
    "inspector.ruleTools": "工具",
    "inspector.rulePaths": "路径",
    "inspector.ruleCwds": "工作目录",
    "inspector.ruleCommands": "命令模式",
    "inspector.testPassed": "通过",
    "inspector.testFailed": "失败",
    "inspector.testSkipped": "跳过",
    "inspector.testTotal": "总数",
    "inspector.qualityPassed": "通过",
    "inspector.qualityFailed": "失败",
    "inspector.gitFiles": "文件数",
    "inspector.gitLines": "行数",
    "inspector.gitAvailable": "Git可用",
    "inspector.yes": "是",
    "inspector.no": "否",
    "inspector.openEvidence": "在预览中打开",
    "inspector.openDiff": "打开差异",
    "inspector.preview": "预览",
    "inspector.log": "日志",
    "inspector.runtimeSource": "来源",
    "inspector.runtimeReady": "托管工具就绪",
    "inspector.runtimeResolvedRoots": "解析路径",
    "inspector.runtimeToolSources": "工具来源",
    "inspector.runtimeWarnings": "告警",
    "inspector.sessionStatus": "会话状态",
    "inspector.lastState": "最后状态",
    "inspector.lastStateMessage": "最后状态详情",
    "inspector.timelineProjection": "时间线投影",
    "inspector.recentTransitions": "最近状态迁移",
    "inspector.noRecentTransitions": "当前没有最近状态迁移。",

    "inspector.noTodos": "本次会话暂无待办。",
    "inspector.noArtifacts": "暂无产物。",
    "inspector.noPlan": "当前会话暂无计划。",
    "inspector.noRecipes": "当前未检测到工作区 recipe。",
    "inspector.noProblems": "当前没有诊断或失败测试。",
    "inspector.noReview": "当前还没有审查结果。",
    "inspector.noReviewFindings": "当前没有结构化问题。",
    "inspector.noReviewEvidence": "当前没有结构化证据。",
    "inspector.noPermissions": "当前没有权限上下文。",
    "inspector.noRuntime": "当前没有运行环境上下文。",
    "inspector.noPermissionRules": "当前没有配置权限规则。",
    "inspector.noPreview": "选择文件或产物以预览。",
    "inspector.noLog": "暂无事件。",
    "inspector.noRuntimeWarnings": "当前没有运行环境告警。",

    "inspector.inputRequired": "需要输入",
    "inspector.customAnswer": "或输入自定义回答…",
    "inspector.submit": "提交",

    "composer.placeholder": "输入消息，Enter 发送，Shift+Enter 换行",
    "composer.send": "发送",
    "composer.stop": "停止",

    "header.refresh": "刷新",
    "header.toggleInspector": "切换检查面板",

    "timeline.thinking": "思考中…",
    "timeline.thinkingLabel": "思考",
    "timeline.thinkingWords": "{n} 词",
    "timeline.stepLabel": "步骤 {n}",
    "timeline.toolDetails": "详情",
    "timeline.diffChanges": "文件变更",
    "timeline.runningToolchain": "工具链步骤执行中…",
    "timeline.runningCommand": "命令执行中…",
    "timeline.runningGit": "Git 操作执行中…",
    "timeline.toolchainTests": "{n} 个失败测试",
    "timeline.toolchainDiagnostics": "{n} 条诊断",
    "timeline.commandExitCode": "退出码 {n}",
    "timeline.gitFilesChanged": "{n} 个变更文件",
    "timeline.gitEntries": "{n} 条 Git 记录",
    "timeline.qualityPassed": "质量门已通过",
    "timeline.qualityFailed": "{n} 条质量门原因",
    "timeline.todoCount": "{n} 个待办",
    "timeline.residualRisks": "残余风险",
    "timeline.compacted": "上下文已压缩",
    "timeline.compactSummarized": "摘要",
    "timeline.compactRetained": "保留",
    "timeline.toolInterrupted": "已取消",
    "timeline.toolDiscarded": "已跳过（重试边界）",
    "timeline.maxTurnsReached": "已达到 {max} 轮上限（已用 {used} 轮）。如需继续，请继续输入。",
    "timeline.guardStop": "连续操作失败，Agent 已停止。请描述问题或调整方向后重新提交。",
    "timeline.cancelled": "已取消。",
    "inspector.compactRetryCount": "压缩重试次数",
    "inspector.compactBoundaryCount": "压缩边界数",
    "inspector.contextPipelineSteps": "上下文流水线",

    "todos.title": "会话待办",
    "todos.done": "完成",
    "todos.todo": "待办",

    "artifacts.title": "产物",

    "modal.permissionRequired": "需要确认",
    "modal.tool": "工具",
    "modal.showDetails": "展开详情",
    "modal.remember": "本会话记住此类操作",
    "modal.deny": "拒绝",
    "modal.approve": "批准",

    "lang.toggle": "English",
  },
};

/**
 * Translate a key to the given language, with optional {param} substitution.
 * Falls back to "en" then to the key itself.
 */
export function t(key, lang = "en", params = {}) {
  let str = STRINGS[lang]?.[key] ?? STRINGS["en"]?.[key] ?? key;
  for (const [k, v] of Object.entries(params)) {
    str = str.replace(`{${k}}`, String(v));
  }
  return str;
}

export const SUPPORTED_LANGS = ["en", "zh"];
